knp_paginator:
    page_range: 5                       # number of links shown in the pagination menu
    default_options:
        page_name: page                 # page name
        sort_field_name: sort           # sort field
        sort_direction_name: direction  # sort direction
        filter_field_name: filterField  # filter field
        filter_value_name: filterValue  # filter value
        distinct: true                  # ensure distinct results, useful when ORM queries are used with GROUP BY statements
    template:
        pagination: 'knp_pagination/bootstrap_v4_pagination.html.twig'     # pagination template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sortable link template
