vich_uploader:
    db_driver: orm
    mappings:
        recipe_images:
            uri_prefix: /img/recipes
            upload_destination: '%kernel.project_dir%/public/img/recipes'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
